# Generated by Django 5.1.2 on 2024-10-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_food_id_alter_restaurant_id'),
        ('restaurant', '0003_restaurant_user_alter_food_id'),
    ]

    operations = [
    ]
