# Generated by Django 5.1.2 on 2024-10-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_merge_20241023_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
    ]
