# Generated by Django 5.1.2 on 2024-10-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
