# Generated by Django 4.2.16 on 2024-10-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_food_id_alter_restaurant_id'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantowner',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
