# Generated by Django 5.0.2 on 2024-10-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
    ]
