# Generated by Django 5.0.2 on 2024-10-27 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_food_id'),
        ('user_profile', '0002_alter_customerprofile_bio_alter_ownerprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
