# Generated by Django 5.1.2 on 2024-10-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_ownerprofile_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='bio',
            field=models.TextField(),
        ),
    ]
