# Generated by Django 5.1.2 on 2024-10-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='author',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='jumlah_like',
        ),
    ]
