# Generated by Django 5.1.2 on 2024-10-23 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_berita_author_remove_berita_jumlah_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='jumlah_like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
