# Generated by Django 5.0.2 on 2024-10-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_berita_jumlah_like_berita_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
