# Generated by Django 5.1 on 2024-10-23 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_restaurantowner_restaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('konten', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('tanggal_pembaruan', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.restaurantowner')),
                ('jumlah_like', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
