# Generated by Django 5.1.2 on 2024-10-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_restaurantowner_restaurant'),
        ('news', '0003_berita_jumlah_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.restaurantowner'),
        ),
    ]
