# Generated by Django 4.2.16 on 2024-10-24 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_food_id_alter_restaurant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_restaurantowner_restaurant'),
        ('review', '0002_alter_review_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restoran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='authentication.customer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
