# Generated by Django 5.0.2 on 2024-10-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_review_gambar_review_display_name_and_more'),
        ('review', '0004_remove_review_gambar_review_display_name_reviewimage'),
    ]

    operations = [
    ]
