# Generated by Django 4.2.16 on 2024-10-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_review_gambar_review_display_name_and_more'),
        ('review', '0004_remove_review_gambar_review_display_name_reviewimage'),
    ]

    operations = [
    ]
