# Generated by Django 5.0.2 on 2024-10-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_alter_comment_id_alter_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
